// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC-gdP-7Dg-IRb_NEkTFMOqrPP873PxFI',
    appId: '1:289507802463:web:e9aa5b11d41468a9d38aea',
    messagingSenderId: '289507802463',
    projectId: 'projeto-quadrados',
    authDomain: 'projeto-quadrados.firebaseapp.com',
    storageBucket: 'projeto-quadrados.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArSfQUuEdKy8gwrTMpRQNTbm8Ed7oGLSw',
    appId: '1:289507802463:android:9de0606d63497f82d38aea',
    messagingSenderId: '289507802463',
    projectId: 'projeto-quadrados',
    storageBucket: 'projeto-quadrados.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZA8l6gqPtTXrBEL_EEkizrYWrftcgrqQ',
    appId: '1:289507802463:ios:51f739a9ce8d1a92d38aea',
    messagingSenderId: '289507802463',
    projectId: 'projeto-quadrados',
    storageBucket: 'projeto-quadrados.appspot.com',
    iosBundleId: 'com.example.fefoadaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZA8l6gqPtTXrBEL_EEkizrYWrftcgrqQ',
    appId: '1:289507802463:ios:51f739a9ce8d1a92d38aea',
    messagingSenderId: '289507802463',
    projectId: 'projeto-quadrados',
    storageBucket: 'projeto-quadrados.appspot.com',
    iosBundleId: 'com.example.fefoadaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC-gdP-7Dg-IRb_NEkTFMOqrPP873PxFI',
    appId: '1:289507802463:web:2f20df9af268592fd38aea',
    messagingSenderId: '289507802463',
    projectId: 'projeto-quadrados',
    authDomain: 'projeto-quadrados.firebaseapp.com',
    storageBucket: 'projeto-quadrados.appspot.com',
  );

}